### ISSUE TITLE
Design an opsdroid logo/sticker for Hacktoberfest 2019

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/style-guidelines#3]
Whenever anyone contributes to opsdroid [we send them a sticker pack](https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59) to say thank you, we do this all year round and not just for Hacktoberfest. 

This year to make Hacktoberfest a bit more special we want people to contribute designs for a special Hacktoberfest opsdroid sticker. We will print a limited edition run of the winning design and send it out with the sticker packs to everyone who contributes to opsdroid during October.

Competition rules:

-    The sticker design must be some kind of mash up of the [opsdroid logo](https://github.com/opsdroid/style-guidelines/tree/master/logos) and the [Hacktoberfest 2019 branding](https://assets.digitalocean.com/hacktoberfest/hacktoberfest_2019_brand_assets.zip).
- The sticker must include the Hacktoberfest sponsor logos DigitalOcean and DEV, similar to how they are shown in the branding.
-    The winning entry must be [submitted to this repository](https://github.com/opsdroid/style-guidelines/tree/master/stickers/hacktoberfest19) as an SVG and PNG (if you’re new to GitHub don’t be afraid to [ask for help](https://riot.im/app/#/room/#opsdroid-developers:matrix.org) raising your first Pull Request).
-    The winning design will be decided by the opsdroid maintainers based on which ever one is their favourite and no other criteria.
-    Designs will be reviewed the weekend following the 31st of October and the end of Hacktoberfest. Stickers will be printed and shipped as quickly as possible afterwards.
-    It is encouraged to sign your work and even include a short url to your work in the sticker design. Just make it look nice!
- By submitting your work to the competition you are giving permission to the opsdroid community to _copy, distribute, display and make derivative works and remixes based on it_. We will likely share it on social media, print it on stickers and generally show it to people because it's awesome.

Good luck!

**Comment by jacobtomlinson** [comment]
And the winner is.. 

🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁🥁

@blindingstars from @northxsouthco with PR #14 

![Winning entry by blindingstars](https://raw.githubusercontent.com/opsdroid/style-guidelines/d25926ecb01ed1472e2168a9f744bb81aeb33cf5/stickers/hacktoberfest19/blindingstars/sticker-blindingstars.png)

Thank you to everyone who took part, all of your entries were awesome.

**Comment by blindingstars** [comment]
:heart_eyes: Thank you! And what a fun project to work on :)
