### ISSUE TITLE
Can I create a banner?

### ISSUE THREAD

**Issue by MohamedMafaz** [opsdroid/style-guidelines#34]

**Comment by MohamedMafaz** [comment]
Hey @jacobtomlinson 
What is the size for banner?

**Comment by jacobtomlinson** [comment]
[This article](https://blog.hootsuite.com/social-media-image-sizes-guide/) has info on banner sizes.

Looks like Twitter headers are 1500x500, maybe start with that?

**Comment by MohamedMafaz** [comment]
Hey @jacobtomlinson 
Can you take a look at my PR?
